// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClaimMatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ClaimMatch'](arg1, arg2, arg3, arg4);
}

export function CreateDivision(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateDivision'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTournament(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTournament'](arg1, arg2, arg3);
}

export function Finish(arg1) {
  return window['go']['main']['App']['Finish'](arg1);
}

export function GenerateBracket(arg1) {
  return window['go']['main']['App']['GenerateBracket'](arg1);
}

export function GetBracket(arg1) {
  return window['go']['main']['App']['GetBracket'](arg1);
}

export function Ippon(arg1, arg2) {
  return window['go']['main']['App']['Ippon'](arg1, arg2);
}

export function ListAthletes(arg1) {
  return window['go']['main']['App']['ListAthletes'](arg1);
}

export function ListDivisions(arg1) {
  return window['go']['main']['App']['ListDivisions'](arg1);
}

export function ListMatches(arg1) {
  return window['go']['main']['App']['ListMatches'](arg1);
}

export function ListTournaments() {
  return window['go']['main']['App']['ListTournaments']();
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function RecordMatchResult(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RecordMatchResult'](arg1, arg2, arg3, arg4);
}

export function RegisterAthlete(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegisterAthlete'](arg1, arg2, arg3, arg4, arg5);
}

export function Resume(arg1) {
  return window['go']['main']['App']['Resume'](arg1);
}

export function Shido(arg1, arg2) {
  return window['go']['main']['App']['Shido'](arg1, arg2);
}

export function StartMatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartMatch'](arg1, arg2, arg3);
}

export function StartOsaekomi(arg1) {
  return window['go']['main']['App']['StartOsaekomi'](arg1);
}

export function StartPractice(arg1, arg2) {
  return window['go']['main']['App']['StartPractice'](arg1, arg2);
}

export function StopOsaekomi(arg1, arg2) {
  return window['go']['main']['App']['StopOsaekomi'](arg1, arg2);
}

export function WazaAri(arg1, arg2) {
  return window['go']['main']['App']['WazaAri'](arg1, arg2);
}

export function Yuko(arg1, arg2) {
  return window['go']['main']['App']['Yuko'](arg1, arg2);
}
