// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ports} from '../models';

export function ClaimMatch(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateDivision(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.DivisionDTO>;

export function CreateTournament(arg1:string,arg2:string,arg3:string):Promise<main.TournamentDTO>;

export function Finish(arg1:string):Promise<void>;

export function GenerateBracket(arg1:string):Promise<void>;

export function GetBracket(arg1:string):Promise<main.BracketDTO>;

export function Ippon(arg1:string,arg2:number):Promise<void>;

export function ListAthletes(arg1:string):Promise<Array<main.AthleteDTO>>;

export function ListDivisions(arg1:string):Promise<Array<main.DivisionDTO>>;

export function ListMatches(arg1:string):Promise<Array<ports.MatchRow>>;

export function ListTournaments():Promise<Array<main.TournamentDTO>>;

export function Pause(arg1:string):Promise<void>;

export function RecordMatchResult(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function RegisterAthlete(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<main.AthleteDTO>;

export function Resume(arg1:string):Promise<void>;

export function Shido(arg1:string,arg2:number):Promise<void>;

export function StartMatch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartOsaekomi(arg1:string):Promise<void>;

export function StartPractice(arg1:string,arg2:string):Promise<string>;

export function StopOsaekomi(arg1:string,arg2:number):Promise<string>;

export function WazaAri(arg1:string,arg2:number):Promise<void>;

export function Yuko(arg1:string,arg2:number):Promise<void>;
